# Site settings
title: Hank.AI
email: info@hank.ai
description: > # this means to ignore newlines until "baseurl:"
  Delivering responsible artificial intelligence solutions for the medical coding industry.  Human augmentation then profit sharing.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
